2021-07-19 16:56:21.556 +07:00 [INF] Starting web host
2021-07-19 17:04:33.582 +07:00 [INF] Starting web host
2021-07-19 17:07:35.771 +07:00 [INF] Starting web host
2021-07-19 17:12:21.064 +07:00 [INF] Starting web host
2021-07-19 17:26:51.732 +07:00 [INF] Starting web host
2021-07-19 18:51:01.896 +07:00 [INF] Starting web host
2021-07-19 20:28:27.304 +07:00 [INF] Starting web host
2021-07-19 20:30:10.496 +07:00 [INF] Starting web host
2021-07-19 20:40:37.233 +07:00 [INF] Starting web host
2021-07-19 20:41:16.049 +07:00 [INF] Starting web host
2021-07-19 20:43:22.351 +07:00 [INF] Starting web host
2021-07-19 20:43:39.799 +07:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomerProFileAPI.Controllers.CustomerController.GetCustomerLogin(Int32 personId) in D:\Work\SSB SOURCE PROJECT\SSB CUSTOMER PROFILES\CUSTOMERPROFILE\Controllers\CustomerController.cs:line 28
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-19 20:44:28.614 +07:00 [INF] Starting web host
2021-07-19 20:45:00.163 +07:00 [INF] Starting web host
2021-07-19 20:49:05.779 +07:00 [INF] Starting web host
2021-07-19 21:01:33.480 +07:00 [INF] Starting web host
2021-07-19 21:02:38.867 +07:00 [INF] Starting web host
2021-07-19 21:04:39.126 +07:00 [INF] Starting web host
2021-07-19 21:05:35.697 +07:00 [INF] Starting web host
2021-07-19 21:22:57.686 +07:00 [INF] Starting web host
2021-07-19 21:23:39.631 +07:00 [INF] Starting web host
2021-07-19 21:24:23.510 +07:00 [INF] Starting web host
2021-07-19 21:25:12.236 +07:00 [INF] Starting web host
2021-07-19 21:26:29.895 +07:00 [INF] Starting web host
2021-07-19 21:27:46.420 +07:00 [INF] Starting web host
2021-07-19 21:31:43.438 +07:00 [INF] Starting web host
2021-07-19 21:33:42.982 +07:00 [INF] Starting web host
2021-07-19 21:37:45.952 +07:00 [INF] Starting web host
2021-07-19 21:59:02.874 +07:00 [INF] Starting web host
2021-07-19 22:02:01.428 +07:00 [INF] Starting web host
2021-07-19 22:02:09.587 +07:00 [ERR] Failed executing DbCommand (44ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Id], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Id] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Id], [s0].[Id]
2021-07-19 22:02:09.627 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:68ecf678-09d1-4d01-8d5a-fc5306cab6cd
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:68ecf678-09d1-4d01-8d5a-fc5306cab6cd
Error Number:207,State:1,Class:16
2021-07-19 22:03:23.071 +07:00 [INF] Starting web host
2021-07-19 22:03:31.341 +07:00 [ERR] Failed executing DbCommand (41ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Id], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Id] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Id], [s0].[Id]
2021-07-19 22:03:31.378 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:41177d6c-22d1-4d51-b805-557e51cddd70
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:41177d6c-22d1-4d51-b805-557e51cddd70
Error Number:207,State:1,Class:16
2021-07-19 22:04:46.140 +07:00 [INF] Starting web host
2021-07-19 22:04:55.537 +07:00 [ERR] Failed executing DbCommand (55ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Id], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Id] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Id], [s0].[Id]
2021-07-19 22:04:55.577 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:a5be9a8f-087f-40ef-af34-870fa4d2ce10
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:a5be9a8f-087f-40ef-af34-870fa4d2ce10
Error Number:207,State:1,Class:16
2021-07-19 22:06:35.399 +07:00 [INF] Starting web host
2021-07-19 22:06:42.609 +07:00 [ERR] Failed executing DbCommand (70ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Id], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Id] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Id], [s0].[Id]
2021-07-19 22:06:42.645 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:de929a71-d653-4fd3-a930-ff13eb0f32b8
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:de929a71-d653-4fd3-a930-ff13eb0f32b8
Error Number:207,State:1,Class:16
2021-07-19 22:08:10.326 +07:00 [INF] Starting web host
2021-07-19 22:08:19.378 +07:00 [ERR] Failed executing DbCommand (43ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Customer_SnapshotId], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Customer_SnapshotId] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Customer_SnapshotId], [s0].[Id]
2021-07-19 22:08:19.414 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:71411873-b37d-4090-b91f-50a7de9b239d
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_guid'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:71411873-b37d-4090-b91f-50a7de9b239d
Error Number:207,State:1,Class:16
2021-07-19 22:09:34.552 +07:00 [INF] Starting web host
2021-07-19 22:09:41.913 +07:00 [ERR] Failed executing DbCommand (44ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Customer_SnapshotId], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Customer_SnapshotId] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Customer_SnapshotId], [s0].[Id]
2021-07-19 22:09:41.952 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:09b11c2c-c6d2-44ea-87ee-febcb207cb19
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:09b11c2c-c6d2-44ea-87ee-febcb207cb19
Error Number:207,State:1,Class:16
2021-07-19 22:10:13.765 +07:00 [ERR] Failed executing DbCommand (11ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Customer_SnapshotId], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Customer_SnapshotId] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Customer_SnapshotId], [s0].[Id]
2021-07-19 22:10:13.766 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:09b11c2c-c6d2-44ea-87ee-febcb207cb19
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at CustomerProFileAPI.Services.Customer.CustomerServices.GetCustomerAndPoliciesByPersonId(Int32 personId) in D:\Work\SSB SOURCE PROJECT\SSB CUSTOMER PROFILES\CUSTOMERPROFILE\Services\Customer\CustomerServices.cs:line 36
ClientConnectionId:09b11c2c-c6d2-44ea-87ee-febcb207cb19
Error Number:207,State:1,Class:16
2021-07-19 22:13:30.550 +07:00 [INF] Starting web host
2021-07-19 22:13:39.199 +07:00 [ERR] Failed executing DbCommand (44ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Id], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Id] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Id], [s0].[Id]
2021-07-19 22:13:39.236 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:a226f930-84c0-462c-8218-17451f0b049d
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:a226f930-84c0-462c-8218-17451f0b049d
Error Number:207,State:1,Class:16
2021-07-19 22:13:59.310 +07:00 [ERR] Failed executing DbCommand (11ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Id], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Id] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Id], [s0].[Id]
2021-07-19 22:13:59.312 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:a226f930-84c0-462c-8218-17451f0b049d
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at CustomerProFileAPI.Services.Customer.CustomerServices.GetCustomerAndPoliciesByPersonId(Int32 personId) in D:\Work\SSB SOURCE PROJECT\SSB CUSTOMER PROFILES\CUSTOMERPROFILE\Services\Customer\CustomerServices.cs:line 36
ClientConnectionId:a226f930-84c0-462c-8218-17451f0b049d
Error Number:207,State:1,Class:16
2021-07-19 22:14:10.916 +07:00 [ERR] Failed executing DbCommand (10ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Id], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Id] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Id], [s0].[Id]
2021-07-19 22:14:10.917 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:a226f930-84c0-462c-8218-17451f0b049d
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at CustomerProFileAPI.Services.Customer.CustomerServices.GetCustomerAndPoliciesByPersonId(Int32 personId) in D:\Work\SSB SOURCE PROJECT\SSB CUSTOMER PROFILES\CUSTOMERPROFILE\Services\Customer\CustomerServices.cs:line 36
ClientConnectionId:a226f930-84c0-462c-8218-17451f0b049d
Error Number:207,State:1,Class:16
2021-07-19 22:25:25.772 +07:00 [INF] Starting web host
2021-07-19 22:25:36.690 +07:00 [ERR] Failed executing DbCommand (44ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Id], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Id] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Id], [s0].[Id]
2021-07-19 22:25:36.727 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:86ddaa4b-00cc-45fa-9fba-7765d92aa880
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:86ddaa4b-00cc-45fa-9fba-7765d92aa880
Error Number:207,State:1,Class:16
2021-07-19 22:33:22.764 +07:00 [INF] Starting web host
2021-07-19 22:33:31.243 +07:00 [ERR] Failed executing DbCommand (44ms) [Parameters=[@__personId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [s].[Id], [s].[Birthdate], [s].[Customer_guid], [s].[Email], [s].[FirstName], [s].[IdentityCard], [s].[LastName], [s].[LastUpdated], [s].[LineID], [s].[PersonId], [s].[PrimaryPhone], [s].[SecondaryPhone], [s].[TitleId], [s].[WorkAddress1], [s].[WorkAddress2], [s].[WorkAddressDistrict], [s].[WorkAddressId], [s].[WorkAddressName], [s].[WorkAddressProvince], [s].[WorkAddressSubDistrict], [s].[WorkAddressSubDistrictCode], [s].[WorkAddressZipCode], [s0].[Id], [s0].[ApplicationCode], [s0].[CustName], [s0].[CustPersonId], [s0].[Customer_SnapshotId], [s0].[Customer_guid], [s0].[LastUpdated], [s0].[PayerName], [s0].[Payer_guid], [s0].[PersonId], [s0].[Premium], [s0].[Product], [s0].[ProductType]
FROM [ss].[SnapCustomer] AS [s]
LEFT JOIN [ss].[SnapPolicy] AS [s0] ON [s].[Id] = [s0].[Customer_SnapshotId]
WHERE [s].[PersonId] = @__personId_0
ORDER BY [s].[Id], [s0].[Id]
2021-07-19 22:33:31.280 +07:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CustomerProFileAPI.Data.AppDBContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:5e285d3b-0e16-4db2-b964-579a96ae4f42
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Customer_SnapshotId'.
Invalid column name 'Customer_SnapshotId'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:5e285d3b-0e16-4db2-b964-579a96ae4f42
Error Number:207,State:1,Class:16
2021-07-19 22:35:48.335 +07:00 [INF] Starting web host
2021-07-19 22:46:28.094 +07:00 [INF] Starting web host
2021-07-19 22:48:39.439 +07:00 [INF] Starting web host
2021-07-19 22:50:21.600 +07:00 [INF] Starting web host
2021-07-19 22:51:52.832 +07:00 [INF] Starting web host
2021-07-19 22:53:18.386 +07:00 [INF] Starting web host
2021-07-19 22:56:19.075 +07:00 [INF] Starting web host
2021-07-19 22:57:32.427 +07:00 [INF] Starting web host
2021-07-19 22:58:50.369 +07:00 [INF] Starting web host
